### ISSUE TITLE
Multiple ticket entries in listing page

### ISSUE THREAD

**Issue by jibijohndavid** [beingnin/carsofti#3]
### Multiple entries in **ticket listing** page ###

**Steps to reproduce the behavior:**

1. Go to 'http://carsofti.com/Registration/Tickets'
2. Find entry with ticket id  **'21029300'**
3. Three entries for the same are showed with same id and different estimate id

**Expected behavior**
A single entry for a ticket must be listed only

**Screenshots**
![capture](https://user-images.githubusercontent.com/25331085/42801752-42d0e3cc-89be-11e8-9911-1992ab59ae53.PNG)

**Comment by Anoop-Parackel** [comment]
Isuue has been solved
